In [ ]:
## 앙상블

In [2]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier

In [5]:
X = np.load("titanic_X_train.npy")
y = np.load("titanic_y_train.npy")

In [7]:
X[0]


array([0.27345609, 0.01415106, 0.        , 1.        , 0.        ,
       0.125     , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [9]:
y[:10]


array([0., 1., 1., 1., 0., 0., 0., 0., 1., 1.])

In [12]:
clf1 = LogisticRegression(random_state=1)
clf2 = DecisionTreeClassifier(random_state=1, max_depth=4)
clf3 = GaussianNB()
eclf = VotingClassifier(
estimators=[('lr', clf1), ('rf', clf2), ('gnb',clf3)], voting='hard')

In [14]:
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, X, y, cv=5).mean()


0.8222941661905668

In [15]:
cross_val_score(clf1, X, y, cv=5).mean()

0.8290420872214816

In [16]:
cross_val_score(clf2, X, y, cv=5).mean()

0.8223068621849807

In [17]:
cross_val_score(clf3, X, y, cv=5).mean()

0.4600139655938551

In [19]:
eclf = VotingClassifier(
estimators=[('lr', clf1), ('rf', clf2)], voting='hard')
cross_val_score(eclf, X, y, cv=5).mean()

0.8301783787215135

In [21]:
clf1 = LogisticRegression(random_state=1)
clf2 = DecisionTreeClassifier(random_state=1)
eclf = VotingClassifier(estimators=[('lr', clf1), ('dt', clf2)], voting='hard')


In [22]:
c_params = [0.1, 5.0, 7.0, 10.0, 15.0, 20.0, 100.0]
params ={
"lr__solver" : ['liblinear'], "lr__penalty" : ["l2"], "lr__C" : c_params,
"dt__criterion" : ["gini", "entropy"],
"dt__max_depth" : [10,8,7,6,5,4,3,2],
"dt__min_samples_leaf": [1,2,3,4,5,6,7,8,9]
}

In [23]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5)
grid = grid.fit(X, y)
grid.best_score_

0.8425569732749316

In [24]:
grid.best_params_


{'dt__criterion': 'gini',
 'dt__max_depth': 10,
 'dt__min_samples_leaf': 5,
 'lr__C': 5.0,
 'lr__penalty': 'l2',
 'lr__solver': 'liblinear'}

In [25]:
## 보팅

In [27]:
clf1 = LogisticRegression(random_state=1)
clf2 = DecisionTreeClassifier(random_state=1, max_depth=4)
clf3 = GaussianNB()
eclf = VotingClassifier(
estimators=[('lr', clf1), ('rf', clf2), ('gnb',clf3)], voting='hard')

In [29]:
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, X, y, cv=5).mean()


0.8222941661905668

In [30]:
cross_val_score(clf1, X, y, cv=5).mean()


0.8290420872214816

In [32]:
cross_val_score(clf2, X, y, cv=5).mean()


0.8223068621849807

In [33]:
cross_val_score(clf3, X, y, cv=5).mean()


0.4600139655938551

In [34]:
eclf = VotingClassifier(
estimators=[('lr', clf1), ('rf', clf2)], voting='hard')
cross_val_score(eclf, X, y, cv=5).mean()


0.8301783787215135

In [36]:
clf1 = LogisticRegression(random_state=1)
clf2 = DecisionTreeClassifier(random_state=1)
eclf = VotingClassifier(estimators=[('lr', clf1), ('dt', clf2)], voting='hard')


In [37]:
c_params = [0.1, 5.0, 7.0, 10.0, 15.0, 20.0, 100.0]
params ={
"lr__solver" : ['liblinear'], "lr__penalty" : ["l2"], "lr__C" : c_params,
"dt__criterion" : ["gini", "entropy"],
"dt__max_depth" : [10,8,7,6,5,4,3,2],
"dt__min_samples_leaf": [1,2,3,4,5,6,7,8,9]
}

In [38]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5)
grid = grid.fit(X, y)
grid.best_score_


0.8425569732749316

In [40]:
 grid.best_params_

{'dt__criterion': 'gini',
 'dt__max_depth': 10,
 'dt__min_samples_leaf': 5,
 'lr__C': 5.0,
 'lr__penalty': 'l2',
 'lr__solver': 'liblinear'}

In [42]:
##랜덤포레스트

In [44]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
X = np.load("titanic_X_train.npy")
y = np.load("titanic_y_train.npy")
clf1 = LogisticRegression(random_state=1)
eclf = BaggingClassifier(clf1, oob_score=True)
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, X, y, cv=5).mean() 

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_bagging.py:707: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  "Some inputs do not have OOB scores. "
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_bagging.py:712: RuntimeWarning: invalid value encountered in true_divide
  oob_decision_function = predictions / predictions.sum(axis=1)[:, np.newaxis]
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_bagging.py:707: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  "Some inputs do not have OOB scores. "
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_bagging.py:712: RuntimeWarning: invalid value encountered in true_divide
  oob_decision_function = predictions / predictions.sum(axis=1)[:, np.newaxis]
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_bagging.py:707: UserWar

0.823411413698978

In [45]:
params ={
"n_estimators" : [10,20,30,40,50,55],
"max_samples" : [0.5,0.6,0.7,0.8,0.9,1] 
}
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5)
grid = grid.fit(X, y)
grid.best_score_


/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_bagging.py:707: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  "Some inputs do not have OOB scores. "
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_bagging.py:712: RuntimeWarning: invalid value encountered in true_divide
  oob_decision_function = predictions / predictions.sum(axis=1)[:, np.newaxis]
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_bagging.py:707: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  "Some inputs do not have OOB scores. "
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_bagging.py:712: RuntimeWarning: invalid value encountered in true_divide
  oob_decision_function = predictions / predictions.sum(axis=1)[:, np.newaxis]
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_bagging.py:707: UserWar

0.8313083222243384

In [46]:
grid.best_params_

{'max_samples': 0.9, 'n_estimators': 10}

In [47]:
grid.best_estimator_.oob_score_


0.8211473565804275

In [48]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
X = np.load("titanic_X_train.npy")
y = np.load("titanic_y_train.npy")
eclf = RandomForestClassifier(n_estimators=100, max_features=2, n_jobs=7, oob_score=True)
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, X, y, cv=5).mean()


0.7975623690725576

In [49]:
from sklearn.model_selection import GridSearchCV
params ={
"n_estimators" : [10, 20, 30, 50, 100],
"max_features" : [1,2,3,4,5,6,7, 10, 15, 20, 25, len(X[0])]
}
grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5)
grid = grid.fit(X, y)
grid.best_score_


/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:564: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:564: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:564: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:564: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:564: UserWarning: Some inputs do not have OOB scores. Thi

0.8245730971878371

In [50]:
grid.best_params_


{'max_features': 27, 'n_estimators': 20}

In [51]:
grid.best_estimator_.oob_score_


0.7975253093363329

In [52]:
##부스팅

In [54]:
import numpy as np
X = np.load("titanic_X_train.npy")
y = np.load("titanic_y_train.npy")


In [57]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
eclf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=2), n_estimators=500)

In [58]:
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, X, y, cv=5).mean()

0.7919380435472609

In [59]:
from sklearn.ensemble import RandomForestClassifier
eclf = RandomForestClassifier(n_estimators=500)
cross_val_score(eclf, X, y, cv=5).mean()


0.8009395035866185

In [60]:
eclf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=2), n_estimators=500)
params = {"base_estimator__criterion" : ["gini", "entropy"],
"base_estimator__max_features" : [7,8,],
"base_estimator__max_depth" : [1,2],
"n_estimators": [23,24, 25, 26, 27],
"learning_rate": [0.4, 0.45, 0.5, 0.55, 0.6]
}
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=eclf, param_grid=params, cv=5, n_jobs=7)
grid = grid.fit(X, y)
grid.best_score_


0.8369199517552213

In [61]:
grid.best_params_


{'base_estimator__criterion': 'entropy',
 'base_estimator__max_depth': 2,
 'base_estimator__max_features': 7,
 'learning_rate': 0.4,
 'n_estimators': 25}

In [63]:
grid.best_estimator_.feature_importances_


array([0.1811084 , 0.22622398, 0.01452873, 0.11139787, 0.04945437,
       0.10283734, 0.01658543, 0.01083555, 0.00107955, 0.04053884,
       0.01811405, 0.        , 0.0115603 , 0.03315654, 0.        ,
       0.08206758, 0.01400936, 0.00546183, 0.02364453, 0.        ,
       0.        , 0.0211146 , 0.01489732, 0.0082282 , 0.        ,
       0.        , 0.01315564])